version: '3'

services:
  galene:
    image: deburau/galene:0.6.1
    container_name: galene
    restart: always
    volumes:
      - ./data:/data
      - ./groups:/groups
      - ./recordings:/recordings
      - ./profiles:/profiles
    networks:
      traefik:
    environment:
      - WAIT_HOSTS=1.2.3.4:5349
      - WAIT_LOGGER_LEVEL=info
      - WAIT_HOSTS_TIMEOUT=60
      - WAIT_AFTER_HOSTS=1
      - WAIT_SLEEP_INTERVAL=5
      - GALENE_CPUPROFILE=/profiles/cpu.profile
      - GALENE_DATA=/data
      - GALENE_GROUPS=/groups
      - GALENE_HTTP=:80
      - GALENE_INSECURE=1
      - GALENE_MDNS
      - GALENE_MEMPROFILE/profiles/mem.profile
      - GALENE_MUTEXPROFILE/profiles/mutex.profile
      - GALENE_RECORDINGS=/recordings
      - GALENE_REDIRECT
      - GALENE_RELAY_ONLY
      - GALENE_STATIC
      - GALENE_TURN=
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      - "traefik.http.routers.galene.rule=Host(`galene.example.com`)"
      - "traefik.http.routers.galene.entrypoints=websecure"
      - "traefik.http.routers.galene.tls=true"
      - "traefik.http.routers.galene.tls.domains[0].main=galene.example.com"
      - "traefik.http.routers.galene.service=galene"
      - "traefik.http.services.galene.loadbalancer.server.port=80"
      - "traefik.http.services.galene.loadbalancer.server.scheme=http"
      - "traefik.http.services.galene.loadbalancer.passhostheader=true"

networks:
  traefik:
    external: true
